import csv

with open("Json to csv/test.csv", 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        print(row)

Results = """
['javascript;https://github.com/javascript;https://avatars.githubusercontent.com/u/48139711?v=4']
[]
['javascript-tutorial;https://github.com/javascript-tutorial;https://avatars.githubusercontent.com/u/49552305?v=4']
[]
['javascripter;https://github.com/javascripter;https://avatars.githubusercontent.com/u/13040?v=4']
[]
['javascriptit;https://github.com/javascriptit;https://avatars.githubusercontent.com/u/14077111?v=4']       
[]
['hyperlink;https://github.com/hyperlink;https://avatars.githubusercontent.com/u/133309?v=4']
[]
['JavaScriptErika;https://github.com/JavaScriptErika;https://avatars.githubusercontent.com/u/19316487?v=4'] 
[]
['JavascriptDeNoobAPro;https://github.com/JavascriptDeNoobAPro;https://avatars.githubusercontent.com/u/72440926?v=4']
[]
['javascript-forks;https://github.com/javascript-forks;https://avatars.githubusercontent.com/u/6993497?v=4'][]
['javascriptDev;https://github.com/javascriptDev;https://avatars.githubusercontent.com/u/4343200?v=4']      
[]
['javascriptdezero;https://github.com/javascriptdezero;https://avatars.githubusercontent.com/u/44194645?v=4']
[]
['JavascriptMick;https://github.com/JavascriptMick;https://avatars.githubusercontent.com/u/905728?v=4']     
[]
['AmyDayday;https://github.com/AmyDayday;https://avatars.githubusercontent.com/u/4569236?v=4']
[]
['javascript666666;https://github.com/javascript666666;https://avatars.githubusercontent.com/u/25980255?v=4']
[]
['javascripto;https://github.com/javascripto;https://avatars.githubusercontent.com/u/16804522?v=4']
[]
['javascriptacademy-stash;https://github.com/javascriptacademy-stash;https://avatars.githubusercontent.com/u/70600380?v=4']
[]
['javascripteverywhere;https://github.com/javascripteverywhere;https://avatars.githubusercontent.com/u/44604333?v=4']
[]
['luckyscc;https://github.com/luckyscc;https://avatars.githubusercontent.com/u/22893023?v=4']
[]
['JavascriptIsMagic;https://github.com/JavascriptIsMagic;https://avatars.githubusercontent.com/u/2086868?v=4']
[]
['javascript-indonesias;https://github.com/javascript-indonesias;https://avatars.githubusercontent.com/u/28702747?v=4']
[]
['javascript-ninja-123;https://github.com/javascript-ninja-123;https://avatars.githubusercontent.com/u/19541825?v=4']
[]
['javascriptextjs;https://github.com/javascriptextjs;https://avatars.githubusercontent.com/u/13724723?v=4'] 
[]
['javascript-queen;https://github.com/javascript-queen;https://avatars.githubusercontent.com/u/90614620?v=4']
[]
['javascriptisscary;https://github.com/javascriptisscary;https://avatars.githubusercontent.com/u/13318285?v=4']
[]
['JavaScript-Resource;https://github.com/JavaScript-Resource;https://avatars.githubusercontent.com/u/18742886?v=4']
[]
['javaScriptKampala;https://github.com/javaScriptKampala;https://avatars.githubusercontent.com/u/60253830?v=4']
[]
['javascript-obfuscator;https://github.com/javascript-obfuscator;https://avatars.githubusercontent.com/u/23015672?v=4']
[]
['javascriptlove;https://github.com/javascriptlove;https://avatars.githubusercontent.com/u/1811732?v=4']
[]
['JavaScript-Packer;https://github.com/JavaScript-Packer;https://avatars.githubusercontent.com/u/12014234?v=4']
[]
['JavaScriptNoob;https://github.com/JavaScriptNoob;https://avatars.githubusercontent.com/u/26487438?v=4']
[]
"""